const BERICHTE = {
  ERF1: {
    NAME: "Hannah",
    DATUM: "August 2022",
    CONTENT: [
      "Am 12.09.2021 stieg ich in den Flieger, der mich zu meiner Gastfamilie, die ich bisher nur von wenigen Nachrichten und Bildern kannte, bringen sollte. In Sevilla angekommen erwartete mich meine Gastfamilie, sowie Angela von Interkultur und wir machten uns auf den Weg in mein Zuhause für die nächsten 3 Monate. Die für mich größte Umstellung war definitiv der Tagesablauf, da in meiner Familie praktisch nie vor 15 Uhr Mittag, beziehungsweise vor 22 Uhr abends gegessen wurde.",
      "Aber auch daran gewöhnt man ziemlich schnell und nachdem es zuerst etwas Probleme mit meinem Schulplatz gab, um welche sich das Team von Interkultur aber direkt kümmerte, kam auch schon mein erster Schultag. Die Befürchtung, niemanden kennenzulernen, war tatsächlich grundlos und so war ich in meiner ersten Pause direkt von meiner ganzen Klasse umzingelt. Schnell bildete sich auch eine engere Freundesgruppe, mit der ich auch jetzt, zurück in Deutschland, noch in Kontakt stehe.",
      "Die Schultage in Spanien sind in 2 dreistündige Blöcke unterteilt, sodass man jeden Tag bis ungefähr 15 Uhr Schule hat. Ich hatte unglaubliches Glück mit allen meinen Lehrern und durfte im Unterricht sowie in den Arbeiten grundsätzlich Google-Übersetzer nutzen. Ich bin auch, obwohl ich nur für 3 Monate in Spanien war, direkt am Anfang in einen Sportverein eingetreten, was ich jedem nur ans Herz legen kann, da Spanier nachmittags zum einen nicht wirklich etwas unternehmen und man zum anderen auf diesem Weg noch viel mehr Menschen kennenlernen kann.",
      "Insgesamt habe ich während meiner Zeit in Spanien auch viel mit anderen Austauschschülern aus anderen Ländern unternommen, was unglaublich interessant war und wodurch ebenso enge Freundschaften entstanden sind (der Spanien-Urlaub im nächsten Sommer ist in Planung :D). Im Endeffekt war übrigens nicht das Kennenlernen neuer Freunde, der Abschied in Deutschland oder Heimweh das größte Problem, sondern sich wieder von all den Menschen, die einem so sehr ans Herz gewachsen sind, zu verabschieden.",
      "Alles in allem kann ich mich nur bei Interkultur bedanken, da sie mir eine top organisierte und einmalige Zeit in Spanien ermöglicht haben!",
    ],
  },
  ERF2: {
    NAME: "Hannahs Eltern",
    DATUM: "August 2022",
    CONTENT: [
      "Anfang 2021 kam unsere damals 15jährige Tochter Hannah auf uns zu der Frage, ob wir mit einem Auslandsaufenthalt in der kommenden 11. Klasse des Gymnasiums einverstanden wären.Mitten in der Corona-Krise keine leichte Entscheidung. Erst wollte Hannah unbedingt 1 Jahr (!) nach Australien, was für uns als Eltern einer dann 16jährigen nicht in Frage kam. ",
      "Schließlich fand sie über das Internet eine sehr interessante Alternative: die Organisation “Interkultur”. Wir schrieben Carson Bohlmann von InterKultur per E-Mail an und von da an begann ein reger, immer zeitnaher und sehr sympathischer Kontakt. Wir fühlten uns schon im Vorfeld von der Organisation sehr gut beraten und aufgehoben. Natürlich gab es einiges zu erledigen. Arztbesuch wegen eines Attests, dass Hannah reisen konnte. Ein Gespräch mit Hannah`s Schuldirektor. Diverse Unterlagen, die auszufüllen waren. Aber alles gut machbar .",
      "Auch fanden Video Calls einige Monate vor der Abreise statt und man konnte quasi “face-to-face” wirklich alles klären, was uns wichtig war.",
      "3-4 Monate vor Abflug erhielten wir per Email auch Fotos und eine Art Lebenslauf aller Mitglieder der Gastfamilie in Dos Hermanas / Sevilla. Alles lief wie am Schnürchen und die Aufregung stieg so langsam. Der Abreisetag war nicht mehr weit.",
      "Dadurch, dass Hannah zu diesem Zeitpunkt bereits zweimal geimpft war, gab es auch diesbezüglich überhaupt keine Probleme.",
      "Am 12.09.2021 war es dann soweit: wir fuhren Hannah mit einem 23kg-Koffer und Handgepäck nach Frankfurt an den Flughafen. Das Abenteuer konnte beginnen.",
      "Eins noch: einfach war es für uns als Eltern nicht. Die ersten 1-2 Wochen besonders. Aber von da an wurde es immer besser: durch regelmäßige Telefonate und WhatsApp`s hielten wir quasi täglich Kontakt zu unserer Tochter, was wirklich gut war.",
      "Leider begann die Schule nicht wie geplant am 15.09. sondern eine Woche später. Dafür war Interkultur aber nicht verantwortlich. Es gab wohl von Seiten der Schule Gründe, warum nicht sofort mit dem Unterricht gestartet wurde. Aber nach einer Woche lief alles wie am Schnürchen und eine Routine trat ein. Der Unterricht war täglich von 8.15 bis 14.45 Uhr.",
      "Es fanden Treffen der Schülerinnen und Schüler statt, welche ein Trimester bzw. ein ganzes Schuljahr in Andalusien verbrachten und dicke Freundschaften entstanden, die bis heute anhalten.",
    ],
  },
  ERF3: {
    NAME: "Martina",
    DATUM: "Frühlingsemester 2010",
    CONTENT: [
      "Am 15. Jänner ging es los. Ich war schon sehr gespannt und neugierig auf die nächsten 6 Monate. Am Vortag hatte ich mich noch von all meinen Freunden verabschieden müssen, was wirklich schwierig war, denn ich wusste, dass es so lange Zeit ohne sie sehr hart werden würde. ",
      "Nun stand ich da mit meiner Familie am Flughafen, und wir kamen zur Passkontrolle, wo ich mich von ihnen verabschieden musste. Diesen Moment hatte ich schon die ganze Zeit hinausgezögert, weil ich wusste, dass dieser einer der schwersten überhaupt war.",
      "Ich war natürlich furchtbar angespannt und dachte mir „Wieso mache ich so etwas nur? Wie komme ich auf einmal auf die Idee, ein halbes Jahr von zu Hause wegzufahren? Bin ich reif genug, das alleine zu schaffen, nach Spanien zu fahren, ohne auch nur irgendjemanden dort zu kennen?",
      "Plötzlich wurde ich sehr skeptisch und wusste nicht was ich tun sollte, doch diese Nervosität verging dann eigentlich im Flugzeug sehr bald, denn ich hatte das Glück das ich einen sehr bekannten österreichischen Sportler kennen lernen durfte und das lenkte mich vom Abschiedsschmerz sehr ab.",
      "In Barcelona angekommen, wusste ich erst einmal nicht wohin, da der Flughafen sehr groß war. Deswegen ging ich einfach der Menschenmenge nach, und das war gut, denn ich bekam sehr schnell meinen Koffer und fand dann auch sofort einen Mitarbeiter von Interkultur, der mich abholte. Er brachte mich zum Bahnhof und ich wartete auf den Zug nach Alicante. Während des Warten sind wieder die üblichen Fragen aufgekommen, denn ich fühlte mich trotz der vielen Menschen im Bahnhof alleine. Nach ungefähr eineinhalb Stunden Wartezeit konnte ich auch schon in den Zug einsteigen. Was mir jedoch am Bahnhof völlig fremd war, war, dass sie sogar hier das Gepäck wie am Flughafen kontrollierten, ich kannte so etwas natürlich nicht, da ich immer nur in Österreich mit dem Zug gefahren bin.",
      "Während der 4-stündigen Bahnfahrt dachte ich schon über meine Gastfamilie nach, wird es wohl für ein halbes Jahr bei einer anfangs fremden Familie leben? Ich machte mir auch Sorgen, ob mein Spanisch gut genug war, um mit den Spaniern kommunizieren zu können und Freunde zu finden. Als ich ankam, wurde ich auch schon am Bahnhof von meiner Gastfamilie und meiner Betreuerin empfangen. Nachdem es sehr spät am Abend war und ich sehr müde und erschöpft ging, schlief ich dann auch sehr bald schlafen, schrieb meiner Familie in Österreich natürlich noch, dass es mir gut ging. ",
      "Ich habe mich in das spanische Leben  nach einiger Zeit eingewöhnt, da der Lebensstil ja doch sehr viele Unterschiede aufweist. Ich brauchte eine Weile, den Abschied von meinen Vertrauten aus Österreich zu verarbeiten und es war am Anfang besonders schwer, kein Heimweh zu haben.  Dazu kam, dass ich mich in meiner Gastfamilie nicht wohl fühlte und nach einigen Wochen den Wunsch, zu einer anderen Familie zu wechseln. Das ging dann glücklicherweise sehr schnell, und schon zwei Tage später war ich bei einer anderen Gastfamilie untergebracht, die ich zuvor schon von der Schule gekannt hatte. Von diesem Zeitpunkt an genoss ich einfach jeden Moment in Spanien. Ich lernte sehr schnell viele Leute kennen, nicht nur Austauschschüler, sondern auch, was mir sehr wichtig war, viele Spanier, denn ich war ja auch gekommen, um gut Spanisch zu lernen. Wir unternehmen sehr oft etwas, auch wenn sie für die Schule lernen müssen, und gingen auch hier und da in Alicante fort.",
      "Jeder Tag war einfach einzigartig toll und ich vermisse die Zeit in Spanien sehr. Der Kontakt zu meinen spanischen Freunden und auch zu den anderen Austauschschülern besteht weiterhin und ich bin mir auch sicher, dass ich sehr bald wieder nach Alicante fahren werde, um meine Freunde und Gastfamilie zu besuchen. Ich kann jedem Jugendlichen ein Austauschjahr empfehlen, denn so eine Chance gibt es nicht oft im Leben und man sollte sie auf jeden Fall nützen. Denn auch wenn es am Anfang sehr schwer ist, wird es von Tag zu Tag immer besser und man kann Spanien voll genießen. ",
    ],
  },
  ERF4: {
    NAME: "Katharina",
    DATUM: "September 2010",
    CONTENT: [
      "Etwa ein Jahr vor meinem Austausch in Spanien hab ich begonnen mir Gedanken zu machen wohin ich gehen sollte. Alle meine Freundinnen haben sich entschlossen in englischsprachige Länder zu gehen, aber ich wollte unbedingt nach Spanien, weil ich das Land einfach liebe. (Außerdem lernte ich damals schon seit 2 Jahren Spanisch in der Schule) Als es um die Entscheidung meiner Stadt ging, hab ich mir ein paar Meinungen von Leuten eingeholt, die mir fast alle sagten, dass sie nach Andalusien gehen würden, weil man dort die typisch spanische Kultur hautnah miterlebt. Außerdem wollte ich unbedingt in eine Stadt und nicht in ein kleines Dorf.",
      "Also hab ich mich erkundigt und stieß schließlich auf Sevilla. Da ich mir nicht sicher war ob es mir dort gefallen würde habe ich mich erst einmal für zwei Monate angemeldet. Die letzten Wochen vor meiner Abreise vergingen wie im Fluge und ich wurde immer nervöser, aber freute mich schon riesig.",
      "Als der Tag gekommen war und ich ins Flugzeug einstieg, ist mir erst einmal bewusst geworden was ich da eigentlich gerade mache und wie verrückt das ganze ist, doch dieses Gefühl verwandelte sich schon bald in große Vorfreude. Als ich in Barcelona gelandet bin, hat mich Ismael am Flughafen empfangen und mich in die Unterkunft für das kommende Vorbereitungswochenende gebracht. Dort lernte ich noch viele andere Mädchen und Jungs kennen, die das selbe wie ich machten und wir uns über unsere Ängste und Zweifel aussprechen konnten. Das Wochenende in Barcelona war zwar kurz, aber trotzdem sehr lustig und ich habe viel über das spanische Leben und die Spanier gelernt, was mir in den kommenden Monaten ziemlich hilfreich war.",
      "Am Sonntag war es dann so weit und wir mussten uns von einigen unserer 'Bekanntschaften' trennen, weil wir in Gruppen, in verschiedene Züge in unsere jeweilige Stadt fuhren. Angekommen in Sevilla, erwartete mich schon meine Gastfamilie, die mich unglaublich herzlich begrüßt hatte und mit mir in mein neues 'Zuhause' fuhr. Die Familie war total lieb und hilfsbereit und hat mir mit meinen Sprachproblemen sehr geholfen. Auch mein Zimmer war super und ich wohnte mitten in der Stadt, nur fünf Minuten von meiner Schule entfernt.",
      "Meine Schule war allgemein wirklich toll! Natürlich darf man das spanische Schulsystem, nicht mit dem aus Österreich oder Deutschland vergleichen, denn in Spanien herrscht totaler Frontalunterricht, woran man sich aber mit der Zeit gewöhnt. Sowohl die Schüler als auch die Lehrer waren alle so unglaublich lieb und halfen mir vom ersten Tag an mit Allem. Obwohl es am Anfang ein bisschen schwer war wegen der Sprache, hab ich doch gleich Anschluss gefunden. (Was bei Spaniern ziemlich leicht ist, denn es ist ein sehr offenes Volk) Meine Freunde und Freundinnen haben mich zu Allem eingeladen und mich überallhin mitgenommen, so dass ich von der Stadt viel erleben und erfahren konnte.",
      "Übrigens ist Sevilla eine traumhafte Stadt! Sie gehört zu einer der schönsten Städte, die ich je gesehen habe und ich kann es nur jeden empfehlen dorthin zu gehen. Für mich war die Größe der Stadt perfekt, nicht zu groß und nicht zu klein. Vor allem die Altstadt ist wahnsinnig schön und man kann im Zentrum alle wichtigen Plätze zu Fuß erreichen und auch sonst gibt es gute Busverbindungen in alle Stadtteile. Besonders beeindruckend waren für mich die Semana Santa(Karwoche) und die Feria de Abril. Diese beiden Feste finden jedes Jahr im Frühling statt und sind in Sevilla besonders berühmt (Jedem der nach Sevilla geht, empfehle ich zu diesen Festen dort zu sein, denn das sind unvergessliche Erlebnisse) Eines der wichtigsten Dinge in Spanien ist, dass du offen bist! In der Schule, mit Freunden, mit deiner Familie...rede so viel wie möglich und zieh dich nicht zurück! Du wirst sehen, dass die Spanier so herzlich, offen und hilfsbereit sind und es gar kein Problem sein wird, dich zu integrieren. In den ersten Wochen ist es immer ein wenig schwierig, weil man sich erst an alles gewöhnen muss und man erst ein paar Leute kennt. Was ich auch gemacht hab (und was ich jedem rate) ist, bei allen Aktivitäten, die dir angeboten werden, mitzumachen. Egal ob bei einer Feier, zum shoppen, einen Ausflug oder sonst irgendetwas, man musst auf jeden Fall mitgehen! Denn solche Dinge können so sehr helfen Freundschaften und Beziehungen zu stärken. Ich hatte zwar oft absolut keine Lust auf etwas, aber ich habe mitgemacht und war im Nachhinein so froh, dass ich es gemacht hatte. Außerdem merken die Spanier dadurch auch, dass du dich bemühst und gerne was mit ihnen unternimmst. Schon nach den ersten Wochen, war ich mir dann sicher, dass ich länger als zwei Monate bleiben möchte, also verlängerte ich auf vier Monate. (Am Ende wollte ich gar nicht mehr weg) Leider vergingen diese vier Monate rasend schnell und meine Abreise näherte sich schon langsam. Die letzten paar Tage kamen meine Eltern zu Besuch nach Sevilla und lernten meine neue „Heimat“ selbst kennen. Auch sie waren fasziniert von der Stadt und der Kultur und verstanden mich gut, dass ich am Liebsten dort geblieben wäre.",
      "Der letzte Tag in der Schule und bei meiner Familie war der Schlimmste! Der Abschied viel mir unendlich schwer und es flossen viele Tränen, doch ich wusste dass ich sie bald wieder besuchen werde. Abschließend kann ich sagen, dass mein Aufenthalt in Sevilla, bis jetzt eine der besten Entscheidungen meines Lebens war und ich sie in keinster Weise bereue.",
      "Ich habe so viel dazu gelernt und bin stolz auf mich, was ich geschafft habe! Nicht nur sprachlich, sondern auch menschlich und kulturell hat mir diese Reise sehr viel gebracht und ich kann nur jedem da draußen raten, so etwas zu machen.",
      "Ich weiß genau wie schwer die Entscheidung ist und wie groß oft die Angst, aber am Ende eure Reise werdet ihr zurückblicken und merken, dass das alles um sonst war. Alles Liebe, Kathi",
    ],
  },
  ERF5: {
    NAME: "Martinas Mutter",
    DATUM: "September 2014",
    CONTENT: [
      "Als meine Tochter Martina erstmals im Sommer 2010 den Wunsch äußerte, ein Semester in Spanien verbringen zu wollen, war ich überrascht. Sie, die so eng mit ihrer Familie und Freunden verbunden ist und erst 15 Jahre alt? So schlug ich ihr vor, einmal Informationsmaterial zu sammeln und alles für einen Aufenthalt in die Wege zu leiten, mit dem Hintergedanken, dass sie mit dieser Arbeit wohl dann das Interesse daran verlieren würde....",
      "Ich war skeptisch und Martinas Vater war gegen einen Aufenthalt in Spanien. Aber Martina blieb hartnäckig bei ihrem Wunsch. Sie suchte im Internet eine Organisation und fand „Interkultur“ mit der sie intensiv kommunizierte. Ich hatte vorher von Interkultur noch nie etwas gehört und daher waren meine Bedenken groß. Aber Martina stellte klar, wenn nach Spanien dann nur mit Interkultur!",
      "Ich spürte, Martina war es ernst, und das kam mir unwirklich vor. Fragen über Fragen tauchten bei mir auf und machten mich unruhig: Wie wird sie alleine nach Spanien kommen? Wird sie bei einer netten Gastfamilie wohnen? Wie wird sie in der Schule aufgenommen werden? Kommt sie mit der spanischen Mentalität und dem spanischen Essen zurecht? Was ist, wenn sie krank wird? Wird sie irgendwo verloren gehen.?",
      "Es folgten dann ein Treffen mit Herrn Carson Bohlmann in Wien, ein langes Telefonat mit Herrn Ismael Nieto, beide Mitarbeiter von Interkultur, und ein Gespräch mit der spanischen Botschaft in Wien, wodurch meine Zweifel zerstreut wurden, und ab diesem Zeitpunkt unterstützte auch ich Martinas Wunsch.",
      "Die letzten Tage vor der Abreise im Jänner 2011 stand ich unter 'Strom'. Haben wir auch wirklich an alles gedacht, Reiseversicherung, Gastgeschenke, Winterkleidung mitnehmen, ja oder nein? Flug richtig gebucht? Erreichen wir rechtzeitig den Flughafen Wien Schwechat , wenn es bei uns ein Schneechaos geben sollte? Immer wieder beantwortete Herr Ismael Nieto, professionell und praktisch sofort meine Mails, ging immer geduldig auf meine Anliegen ein und löste alle Probleme. Schlimm war der Tag vor der Abreise, als sich Martina weinend von ihrer besten Freundin verabschiedete, sodass ich fürchtete, so etwas würde uns auch am Flughafen beim Abschied blühen.",
      "Aber trotz der Anspannung haben wir das gut überstanden. Dann kam die Angst, wird sie wohlbehalten bei ihrer Gastfamilie ankommen??? Mit einem kurzen SMS erlöste Martina uns aber von dieser Sorge, alles war bestens. Wir hatten zu Hause vereinbart, dass sie sich jederzeit bei uns rühren kann, wir aber von uns aus wenig Initiative zur Kontaktaufnahme vor allem anfangs zeigen würden, damit sie sich in Ruhe in ihrer neuen Umgebung einleben kann. Das war für mich natürlich enorm schwierig, aber ich spürte, dass das so für uns am besten ist. Nach wenigen Tagen war mir klar, dass sich Martina schwer tut mit den vielen neuen Eindrücken in der neuen Umgebung, die da auf sie niederprasselten. Ich machte ihr Mut, dass das jeder in ihrer Situation durchmacht, sie solle weiter Kontakt zu ihrer Gastfamilie halten.",
      "Sie bemühte sich. Wir skypten, sie sagte mir, es ginge ihr gut, aber ich spürte, dass das nicht wirklich so war. Meine ganze Familie redete ihr gut zu und gab ihr das Gefühl, sie würde es gut schaffen und sich gut einleben.",
    ],
  },
};

const DATA = {
  BERICHTE,
};
export default DATA;
